services:
  mirakurun:
    build:
      context: .
    image: liebemagi/mirakurun-recisdb:latest
    container_name: mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      DOCKER_NETWORK: host
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    network_mode: host
    devices:
      - /dev/bus:/dev/bus
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
      - /dev/px4video4:/dev/px4video4
      - /dev/px4video5:/dev/px4video5
      - /dev/px4video6:/dev/px4video6
      - /dev/px4video7:/dev/px4video7
      - /dev/px4video8:/dev/px4video8
      - /dev/px4video9:/dev/px4video9
      - /dev/px4video10:/dev/px4video10
      - /dev/px4video11:/dev/px4video11
      - /dev/px4video12:/dev/px4video12
      - /dev/px4video13:/dev/px4video13
      - /dev/px4video14:/dev/px4video14
      - /dev/px4video15:/dev/px4video15
    volumes:
      # ** CAUTION **
      # (default) `/usr/local/mirakurun/*` has been moved to `/opt/mirakurun/*`
      # try:
      #   sudo mv -vf /usr/local/mirakurun /opt/mirakurun
      #   sudo mkdir -p /opt/mirakurun/run /opt/mirakurun/opt /opt/mirakurun/config /opt/mirakurun/data
      # you can change to any location if required.
      - type: bind
        source: ./app/config/
        target: /app-config/
      - type: bind
        source: ./app/data/
        target: /app-data/
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
